/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFollowupRouteImport } from './routes/_authenticated/followup'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedMyAccountRouteImport } from './routes/_authenticated/my-account'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedPersonalRouteImport } from './routes/_authenticated/personal'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupRoute = AuthenticatedFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAccountRoute = AuthenticatedMyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalRoute = AuthenticatedPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followup': typeof AuthenticatedFollowupRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/my-account': typeof AuthenticatedMyAccountRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/followup': typeof AuthenticatedFollowupRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/my-account': typeof AuthenticatedMyAccountRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/followup': typeof AuthenticatedFollowupRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/my-account': typeof AuthenticatedMyAccountRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/personal': typeof AuthenticatedPersonalRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/expenses'
    | '/followup'
    | '/inventory'
    | '/ledger'
    | '/my-account'
    | '/owner'
    | '/personal'
    | '/purchases'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/accounts/$id'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/expenses'
    | '/followup'
    | '/inventory'
    | '/ledger'
    | '/my-account'
    | '/owner'
    | '/personal'
    | '/purchases'
    | '/receipts'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/accounts/$id'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/followup'
    | '/_authenticated/inventory'
    | '/_authenticated/ledger'
    | '/_authenticated/my-account'
    | '/_authenticated/owner'
    | '/_authenticated/personal'
    | '/_authenticated/purchases'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/$id'
    | '/_authenticated/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followup': {
      id: '/_authenticated/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof AuthenticatedFollowupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-account': {
      id: '/_authenticated/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof AuthenticatedMyAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal': {
      id: '/_authenticated/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AuthenticatedPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$id': {
      id: '/_authenticated/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFollowupRoute: typeof AuthenticatedFollowupRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedMyAccountRoute: typeof AuthenticatedMyAccountRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedPersonalRoute: typeof AuthenticatedPersonalRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFollowupRoute: AuthenticatedFollowupRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedMyAccountRoute: AuthenticatedMyAccountRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedPersonalRoute: AuthenticatedPersonalRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
